### ISSUE TITLE
How is it generating the cookie?

### ISSUE THREAD

**Issue by AppleTechy** [wiredprairie/Nest-Thermostat-DotNET-API#2]
I am trying to create an unofficial API on accessing the video stream. I have figured out how to generate an access token and then session token. Is the generation of the cztoken which is just the access token as a permanent cookie.. Do you know how it is generating the session cookie? As the session cookie appears to be how it is authenticating all the the requests sent..? I appreciate any help!

**Comment by wiredprairie** [comment]
No, I do not.
